apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    component: application
data:
  grapevine.config.exs: |
    use Mix.Config

    # Configure your database
    config :grapevine, Grapevine.Repo,
      url: System.get_env("DATABASE_URL")

    config :grapevine, Web.Endpoint,
      url: [host: {:system, "HOST"}, port: 80, scheme: "http"],
      http: [port: 4001],
      server: true,
      cache_static_manifest: "priv/static/cache_manifest.json"

    config :logger, level: :info

    config :phoenix, :serve_endpoints, true

    # Temp
    config :tzdata, autoupdate: :disabled

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-envvars
  labels:
    component: application
data:
  HOST: grapevine-grapevine.grapevine
