apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grapevine
  labels:
    component: application
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: application
    spec:
      containers:
      - name: grapevine
        image: grapevine:latest
        # TODO
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: config-envvars
          - secretRef:
              name: secret-envvars
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        ports:
        - containerPort: 4001
          name: http
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /etc/grapevine.config.exs
          readOnly: true
          subPath: grapevine.config.exs
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: grapevine.config.exs
              path: grapevine.config.exs
