apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    component: migrations
spec:
  template:
    metadata:
      name: migrations
      labels:
        component: migrations
    spec:
      containers:
      - name: grapevine-migrations
        image: grapevine:latest
        # TODO
        imagePullPolicy: IfNotPresent
        args: ['migrate']
        envFrom:
          - configMapRef:
              name: config-envvars
          - secretRef:
              name: secret-envvars
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /etc/grapevine.config.exs
          readOnly: true
          subPath: grapevine.config.exs
      restartPolicy: OnFailure
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: grapevine.config.exs
              path: grapevine.config.exs
