apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
      - name: postgres
        image: postgres:10-alpine
        imagePullPolicy: Always
        env:
        - name: POSTGRES_DB
          value: grapevine
        - name: POSTGRES_PASSWORD
          value: grapevine
        - name: POSTGRES_USER
          value: grapevine
        # livenessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        ports:
        - containerPort: 5432
          name: psql
        # resources:
        #   requests:
        #     cpu: "20m"
        #     memory: "55M"
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    component: database
spec:
  selector:
    component: database
  type: ClusterIP
  ports:
  - name: psql
    port: 5432
    targetPort: psql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
