# https://github.com/GoogleContainerTools/skaffold/blob/f5dbcb3712caae6080d77b02e9b0b6da04bec0fa/examples/annotated-skaffold.yaml

apiVersion: skaffold/v1beta4
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.SKAFFOLD_TAG}}"

  artifacts:
  - image: grapevine
    context: .
    docker: {}

  local:
    push: false
    useDockerCLI: false
    useBuildkit: false

deploy:
  kustomize:
    path: .kube/
    flags:
      global: []
      apply: []
      delete: []
